pub mod errors;
pub mod events;
pub mod schema;
pub mod auth;
pub mod compression;
pub mod storage;
pub mod index;
pub mod snapshot;
pub mod query;
pub mod engine;
pub mod wal;
pub mod observability;
pub mod backup;
pub mod transaction;
pub mod connection;
pub mod migration;
pub mod optimizer;
pub mod encryption;
pub mod replication;
pub mod raft;
pub mod sql;
pub mod rate_limit;
pub mod cache;
pub mod constraints;
pub mod sequences;
pub mod parallel;
pub mod views;
pub mod triggers;
pub mod fulltext;
pub mod window;
pub mod procedures;
pub mod stats;
pub mod query_optimizer;
pub mod adaptive_pool;
pub mod distributed;
pub mod index_strategies;
pub mod mvcc;
pub mod query_plan;
pub mod consensus;
pub mod columnar;
pub mod sql_bridge;
pub mod transaction_snapshot;
pub mod lockfree;
pub mod sql_views;
pub mod stored_procedures;
pub mod streaming;
pub mod vector_search;
pub mod mvcc_engine;
pub mod cost_optimizer;

#[cfg(test)]
mod tests;

pub use engine::Engine;
pub use errors::{DriftError, Result};
pub use events::{Event, EventType};
pub use query::{Query, QueryResult};
pub use schema::Schema;
pub use connection::{EnginePool, EngineGuard, PoolConfig, PoolStats, EnginePoolStats};
pub use rate_limit::{RateLimitConfig, RateLimitManager, RateLimitStats, QueryCost};
pub use auth::{AuthManager, AuthConfig, User, Role, Permission, Session, AuthContext};
